# logback over sfl4j
# https://docs.spring.io/spring-boot/how-to/logging.html
logging:
  config: "classpath:logback-dev.xml"

# Datasources
# https://docs.spring.io/spring-boot/reference/data/sql.html#data.sql.datasource.configuration
# https://docs.spring.io/spring-boot/how-to/data-access.html
business:
  datasource:
    url: "jdbc:mysql://localhost:3306/cotations"
    username: fabien
    password: password
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    max-total: 30
    configuration:
      maximum-pool-size: 30

# JPA with hibernate
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      # https://docs.spring.io/spring-boot/how-to/data-initialization.html#howto.data-initialization.using-hibernate
      # The standard Hibernate property values are create, update, create-drop, validate and none :
      # - create : hibernate first drops existing tables and then creates new tables,
      # - update : the object model created based on the mappings (annotations or XML) is compared with the existing schema,
      #   and then Hibernate updates the schema according to the diff. It never deletes the existing tables
      #   or columns even if they are no longer required by the application,
      # - create-drop : similar to create, with the addition that Hibernate will drop the database after all operations are completed,
      #   typically used for unit testing,
      # - validate : hibernate only validates whether the tables and columns exist; otherwise, it throws an exception,
      # - none : this value effectively turns off the DDL generation.
      ddl-auto: update

# JsonWebToken settings
jwt:
  key: "Ep-zuUl8NTCIbXTYe4UwzToIohllkdlohrMDOvmSpQ18Y-6otlV8ndRSpv8wNLbOXM_bXPMWNt9eao7UaJ7hXA"
  algorithm: HS512
  expiresIn:
    milliseconds: 86400000

# https://swagger.io/docs/specification/v3_0/api-host-and-base-path/
api:
  server:
    base-url: "http://localhost:8080"
    description: "Serveur de développement"
    version: 1

# api version
server:
  servlet:
    context-path: "/v${api.server.version}"

# Internationalization @Schema (description)
springdoc:
  api-docs:
    resolve-schema-properties: true
